services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_DATABASE: "cvoid-service"
      MYSQL_PASSWORD: "Pa55w0rd"
      MYSQL_ROOT_PASSWORD: "Pa55w0rd"
      MYSQL_USER: "cvoid19"
